### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by abelsiqueira** [ufpr-opt/perprof-jors#11]
- [x] Implementation and architecture (abelsiqueira@ee6e794)
  - [x] Parsing process and output
  - [x] Reuse potential (abelsiqueira@9679527)
  - [x] Make new release and update information for new release
  - [x] Review (lrsantos11@a9e1734)

**Comment by abelsiqueira** [comment]
@lrsantos11 I think that there are only the examples remaining to do, and updating the release.
@r-gaia-cs Do you think that the current perprof constitutes a new release (1.1)?

**Comment by lrsantos11** [comment]
Also we should think on:

- [ ] Funding statement and Acknowledgements
- [ ] Harvard style references.

**Comment by abelsiqueira** [comment]
What is there to add about funding and ack?

**Comment by lrsantos11** [comment]
Ack I don't know, but funding, did you developed while receiving grant from
CNPq? My FAPESP grant was finished by then. If not, just leave without it.

---------
Luiz Rafael dos Santos
@lrsantos11

**Comment by abelsiqueira** [comment]
Not for this. Leaving without.

**Comment by abelsiqueira** [comment]
We need to close the next release (see lpoo/perprof-py#129). Need your opinions.

**Comment by r-gaia-cs** [comment]
@lrsantos11 Can you find some time to review all the text?

**Comment by lrsantos11** [comment]
I just started to do it. When it's done, I'll make a pull request.

**Comment by lrsantos11** [comment]
I performed some minor reviews on text. Some bibliography enters were updated. I also added some texts. https://github.com/lrsantos11/perprof-jors/commit/a9e1734312a779c0c8f11cb75976908399f50e50
I still don't know about ACK. Do we need to thank someone.

**Comment by abelsiqueira** [comment]
I don't think we need to thank anyone.

**Comment by lrsantos11** [comment]
I agree. Are we ready to submmit? I was looking at JORS page and there is a fee to publish. 100 pounds. I don't have (I guess) anyway of funding this. Do you have any source?
I'll ask Aurelio.
I'm writing to the editor on the following terms:

>Dear Editor,

>although we know that the fees JORS are charging have the purpose of funding this journal, we want you to consider that we were two PhD students and a undergrad students by the time we developed our package. Because of that, and because it wasn't listed on our grant scholarships proposal, we could not any official funding on that. Now, two of us finished our PhDs and got positions, however, none of us have any  funding resource yet. Consider that Brazil is a developing country with almost no regard to research funding. We ask you to free us from paying the fee, or at least, give us some discount. 

>Best Regards,

>The Authors

**Comment by abelsiqueira** [comment]
Maybe one of our departments has money for this. I brought Raniere here with department funds.
I can ask tomorrow if that's the case. If you could ask yours, that would be good too.
Nevertheless, the e-mail for the editor speaks the truth, so I concur in sending it.

**Comment by r-gaia-cs** [comment]
+1 to ask for waiver to JORS.

**Comment by lrsantos11** [comment]
I asked for funding in the department. Since we don't have postgraduate program, there is no funding on this. I can as for the vice-president on post-graduation affairs, but it is certainly that she won't give money on this.

**Comment by lrsantos11** [comment]
No funding in my department. Let's hope for the waiver.
