### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by abelsiqueira** [ufpr-opt/perprof-jors#25]
@lrsantos11, can you submit this? Or that least prepare for submission, while #11 is still open (I don't think it will for long).

**Comment by lrsantos11** [comment]
I can. I'll write that message posted on #11 inside submission and let's see what their reply is. 
Although the author's guideline insist that they will accept only .odt, I checked with the Editor through twitter and he confirmed that they will accept our submission. I promised to share the template, since it's on CC license, wright?
 I'll let you know about the submission.

**Comment by lrsantos11** [comment]
We need three potential peer-reviewers indications. I though in Paulo Silva and maybe Steve Leyffer. 
@r-gaia-cs, someone of python community would be great. Can you indicate? Any other indication @abelsiqueira?

**Comment by abelsiqueira** [comment]
`s/Steve/Sven/`. He's a possibility, but we haven't implemented his suggestion yet... so I don't know.
Maybe Dominique Orban, since he works with Python too.

**Comment by lrsantos11** [comment]
Ok. I agree on Dominique. Do you agree on Paulo? We need one more if we don't want Sven Leyffer.

**Comment by abelsiqueira** [comment]
I agree on Paulo. I don't have other suggestions at the moment.
If Raniere doesn't propose anyone, then we settle on Sven.

2015-06-01 10:41 GMT-03:00 Luiz-Rafael Santos <notifications@github.com>:

**Comment by lrsantos11** [comment]
@r-gaia-cs It's up to you bro, to indicate someone else or settle with Sven Layer (he was on BRAZOPT, if you remember).

**Comment by r-gaia-cs** [comment]
+1 to 

- Dominique Orban,
- Steve Leyffer, and
- Paulo Silva.

Maybe @mlubin?

**Comment by lrsantos11** [comment]
Perhaps Lubin instead of Leyfer, or should I list the 4 of them?

--
Luiz Rafael dos Santos
@lrsantos11

**Comment by abelsiqueira** [comment]
+1 for Lubin instead of Leyffer.

2015-06-01 13:41 GMT-03:00 Luiz-Rafael Santos <notifications@github.com>:

**Comment by lrsantos11** [comment]
+2 on Lublin instead of Leyffer.

With that in mind, I'll submit now.
May the force be with us.

--
Luiz Rafael dos Santos
@lrsantos11

**Comment by lrsantos11** [comment]
I just submitted. You can close now the issue @abelsiqueira

**Comment by lrsantos11** [comment]
Guys, should we sent a copy of our paper  to optimization online?

**Comment by r-gaia-cs** [comment]
> should we sent a copy of our paper to optimization online?

+1

**Comment by r-gaia-cs** [comment]
@lrsantos11 Thanks for take care of the submission.

**Comment by lrsantos11** [comment]
No problems @r-gaia-cs. You guys did the hard work. I felt obliged to do it. Nevertheless, I'm on the work of making portable to OS X via homebrew. 
@abelsiqueira Should we sent a copy to optimization online? If yes, I can take care of it too.

**Comment by abelsiqueira** [comment]
+1 to Opt Online. Thanks.

**Comment by lrsantos11** [comment]
Guys, check it out my version to Optimization Online. I though that a plain paper would be more suitable lrsantos11@ bbe10003953fd031ed61c34ed94a6d1144864207

**Comment by abelsiqueira** [comment]
I think it's fine.

**Comment by lrsantos11** [comment]
Submitted to OptOnline. Now we can finally close the submission.
