### ISSUE TITLE
Improve reuse section

### ISSUE THREAD

**Issue by rgaiacs** [ufpr-opt/perprof-jors#30]
> 1. If I wanted to extend perprof-py to include a new parser or a new back-end, what would I need to do?
>
> 2. If I wanted to repurpose your code to help chart some other performance metric, would that be possible? If it is possible, would it be sensible?

**Comment by abelsiqueira** [comment]
1 is implemented in #47.
About 2:
  - "Using a different performance metric" means change $r_{s,p}$ right? This is the `set_percent_problems_solved_by_time`. I don't know if re-implementing it would break something. Or if it makes sense to do it in the backend.
  - "Would it be sensible": if it means change $r_{s,p}$, then the data profile says it is sensible.

**Comment by lrsantos11** [comment]
#47 regarded the issue.

**Comment by lrsantos11** [comment]
#47 closed the issue.

**Comment by abelsiqueira** [comment]
Reopening this because we still need to figure out 2.

**Comment by abelsiqueira** [comment]
@rgaiacs, confirm this for me:
Reusing the code to "use a different performance metric" would mean changing `Pprof`'s definition, or implementing it on the backend. So it is not easily obtainable.

**Comment by abelsiqueira** [comment]
I made a PR regarding this. Please @rgaiacs and @lrsantos11 see if you both agree, because it is a negative point (kind of).

**Comment by rgaiacs** [comment]
> Reusing the code to "use a different performance metric" would mean changing Pprof's definition, or implementing it on the backend. So it is not easily obtainable.

The user will need to overwrite `set_percent_problems_solved_by_time` or `Pdata.ppsbt`. If you just want to change for your own use should be super easy. If you want extend perprof to have this two metrics you will need to do some code refactoring.

**Comment by lrsantos11** [comment]
@rgaiacs  explanation:
>The user will need to overwrite `set_percent_problems_solved_by_time` or `Pdata.ppsbt`. If you just want  to change for your own use should be super easy. If you want extend perprof to have this two metrics you will need to do some code refactoring.

should be some how included into the text. That's what you tried to do in #50  @abelsiqueira ?

**Comment by abelsiqueira** [comment]
It is. Something I should change?

**Comment by lrsantos11** [comment]
It's okay. I made some minor suggestions.

**Comment by lrsantos11** [comment]
Issued solved?

**Comment by abelsiqueira** [comment]
Solved
