### ISSUE TITLE
Improve general quality of English

### ISSUE THREAD

**Issue by rgaiacs** [ufpr-opt/perprof-jors#32]

**Comment by rgaiacs** [comment]
Do we have budget to pay for proof-read by a native speaker? I know someone high qualify for this that I can ask for an estimate price.

**Comment by lrsantos11** [comment]
I don't have any budget at all. I can ask for a friend who is a very skilled english speaker (he worked at Stanford for a while and gave english classes) to take a look.

**Comment by lrsantos11** [comment]
I would do it with the help of my friend. But this should be done last.

**Comment by abelsiqueira** [comment]
Done
