### ISSUE TITLE
Mention that benchmark is useful outside of the field of optimization

### ISSUE THREAD

**Issue by rgaiacs** [ufpr-opt/perprof-jors#37]
For example numerical linear algebra.

**Comment by lrsantos11** [comment]
Guys, I found some more papers (through another paper [1] that use it outside optimization 

> Although originally introduced as a tool for evaluating and comparing optimization software, performance profiles are now widely used, and the second author has found them very useful in the context of algorithms for matrix functions (see, for example, Al-Mohy and Higham [2009, 2011, 2012], and Higham [2005, 2008, 2009] and Higham and Lin [2011]).

where the references are
>AL-MOHY, A. H. AND HIGHAM, N. J. 2009. A new scaling and squaring algorithm for the matrix exponential. SIAM J. Matrix Anal. Appl. 31, 3, 970–989.
>AL-MOHY, A. H. AND HIGHAM, N. J. 2011. Computing the action of the matrix exponential, with an application to exponential integrators. SIAM J. Sci. Comput. 33, 2, 488–511.
>AL-MOHY, A. H. AND HIGHAM, N. J. 2012. Improved inverse scaling and squaring algorithms for the matrix logarithm. SIAM J. Sci. Comput. 34, 4, C153–C169.
> HIGHAM, N. J. 2005. The scaling and squaring method for the matrix exponential revisited. SIAM J. Matrix Anal. Appl. 26, 4, 1179–1193.
> HIGHAM, N. J. 2008. Functions of Matrices: Theory and Computation. SIAM, Philadelphia, PA.
> HIGHAM, N. J. 2009. The scaling and squaring method for the matrix exponential revisited. SIAM Rev. 51, 4, 747–764. 
> HIGHAM, N. J. AND LIN, L. 2011. A Schur–Pade ́ algorithm for fractional powers of a matrix. SIAM J. Matrix Anal. Appl. 32, 3, 1056–1078.
> HIGHAM, N. J. AND LIN, L. 2013. An improved Schur–Pade ́ algorithm for fractional powers of a matrix and their Frechet derivatives. MIMS EPrint 2013.1, Manchester Institute for Mathematical Sciences, University of Manchester, UK. (SIAM J. Matrix Anal. Appl. To appear)

Should we include something?

[1]	N. J. Dingle and N. J. Higham, “Reducing the influence of tiny normwise relative errors on performance profiles,” ACM Trans. Math. Softw., vol. 39, no. 4, pp. 1–11, Jul. 2013.

**Comment by abelsiqueira** [comment]
[1] is another possible extension to perprof-py, it can be included in the issues of perprof-py.

I'll add these other references.
