### ISSUE TITLE
Thank the reviewers

### ISSUE THREAD

**Issue by abelsiqueira** [ufpr-opt/perprof-jors#51]

**Comment by abelsiqueira** [comment]
Done

**Comment by lrsantos11** [comment]
What about thank LPOO and IMECC/Unicamp where we developed `perprof-py`?

**Comment by lrsantos11** [comment]
Also, Miles Lublin and I guess there was another guy who gave us some advices, non?

**Comment by abelsiqueira** [comment]
You're right, let's put all that.

**Comment by lrsantos11** [comment]
Closed with #57
