### ISSUE TITLE
Verify the JORS decision again

### ISSUE THREAD

**Issue by abelsiqueira** [ufpr-opt/perprof-jors#52]
After completing everything, verify that the items requested from the reviewers were satisfied.
Every one of us should do it.

**Comment by lrsantos11** [comment]
Guys, I think we should finish this verification in order to allow me and my friend to make some plain english corrections

**Comment by lrsantos11** [comment]
I did a review and in my opinion we covered everything but the english revision. What about you? On the answer to them, I'll post to them the link to the issues related to their requests so they can see what we have done.

**Comment by abelsiqueira** [comment]
I just finished reviewing again. I did a first review when creating issues the other day.

**Comment by abelsiqueira** [comment]
Is #38 done?

**Comment by lrsantos11** [comment]
I just did some text improvement in #72. However I'll ask for my friend to take into accounts this.

**Comment by rgaiacs** [comment]
Looks good to me. I fixed a few typos and push it directly.

**Comment by lrsantos11** [comment]
Looks good to me. I'll close this one. Now, just english improvements.
